import { Link } from "react-router-dom";
import { uptimeBlack, uptimeLight } from "./assets";
import Navbar from "./components/Navbar/Navbar";
import { ContainerScroll } from "./components/ui/container-scroll-animation";
import { useSelector } from "react-redux";
import { useTheme } from "./components/ThemeProvider";
import BigTabsComponent from "./components/ui/BigTabsComponent";

import LandingPageIcons from "./components/ui/LandingPageIcons";
import { TypewriterEffectSmooth } from "./components/ui/typewriter-effect";
import { HoverEffect } from "./components/ui/card-hover-effect";
// import { HeroParallax } from "./components/ui/hero-parallax";
const projects = [
  {
    title: "Uptime Monitoring",
    description:
      "WEBSPY provides real-time monitoring of website availability, allowing users to track the uptime statusof their websites round the clock..In case of downtime incidents, WEBSPY sends instant notification alerts to users via emailensuring timely awareness of any disruptions.",
  },
  {
    title: " SSL  status",
    description:
      "A WEBSPY continuously monitors the validity period of SSL/TLS certificates associated with monitored websites. Users receive early warning alerts when SSL/TLS certificates are nearing expiration, allowing them to take timely action to renew or replace certificates before they expire.",
  },
  {
    title: "Page Insights",
    description:
      "WEBSPY continuously monitors the performance of individual web pages in real-time, providing users with up-to-date insights into page load times, rendering speed, and other performance metrics.The platform calculates and displays the Speed Index for each web page, representing the time it takes    for the page's content to become visually complete and usable to the user.",
  },
  {
    title: "CO2 footprints",
    description:
      " WEBSPY calculates and assesses the carbon footprint associated with website operations, taking into account factor.The platform tracks and records CO2 emissions generated by website activities,providing users with insights into the environmental impact of their digital footprint.",
  },
];


const words = [
  {
    text: "SiteCheck:",
  },
  {
    text: "Monitor Website Health,",
  },
  {
    text: "SSL Expiry,",
  },
  {
    text: " Page Speed, Metrics,and ",
  },
  {
    text: "Carbon Footprint.",
    className: "text-green-500 dark:text-green-500",
  },
];

const LandingPage = () => {
  const { user } = useSelector((state) => state.user);
  const { theme } = useTheme();
  const scrollImage = theme === "light" ? uptimeLight : uptimeBlack;

  return (
    <div>
      <Navbar />
      <div>
      <section className="">
      <div className="flex flex-col items-center justify-center h-[20rem]  ">
      <p className="text-neutral-600 dark:text-neutral-200 text-xs sm:text-base  ">
      The Path to Digital Liberation: Empowering Website Owners with Comprehensive Monitoring Tools
      </p>
      <TypewriterEffectSmooth words={words} />
      <div className="flex flex-col md:flex-row space-y-4 md:space-y-0 space-x-0 md:space-x-4">
        <button className="relative mt-3 inline-flex h-12 overflow-hidden rounded-full p-[0.100rem] dark:p-0.5 focus:outline-none ">
                    <span className="absolute inset-[-1000%] animate-[spin_2s_linear_infinite] bg-[conic-gradient(from_90deg_at_50%_50%,#E2CBFF_0%,#393BB2_50%,#E2CBFF_100%)]" />
                    <Link
                      to="/dashboard"
                      className="inline-flex h-full w-full cursor-pointer items-center justify-center rounded-full bg-muted text-black px-3 py-1 text-sm font-medium dark:bg-slate-950 dark:text-white backdrop-blur-3xl"
                    >
                      {user ? "Go to Dashboard" : "Get Started Now!!"}
                    </Link>
                  </button>
      </div>
    </div>
      </section>
      <section className="space-y-6 pb-6 pt-6 md:pb-12 md:pt-14 lg:py-32">
        <div className="container flex max-w-[84rem] flex-col items-center gap-4 text-center">
          <div className="flex flex-col -mt-32 overflow-hidden">
            <ContainerScroll
              titleComponent={
                <div className="flex flex-col justify-center items-center mb-10">
                 
                  <h1 className="font-heading text-3xl sm:text-5xl md:text-6xl lg:text-7xl font-semibold">
                    WebSpy: Your All-in-One Website Health Monitor
                  </h1>
                  <p className="max-w-[42rem] leading-normal text-muted-foreground sm:text-xl sm:leading-8">
                    Streamline Your Website Management: Monitor Uptime, SSL,
                    Speed, Metrics, and Carbon Footprint Effortlessly
                  </p>
                </div>
              }
            >
              <img
                src={scrollImage}
                alt="DashboardHomePage"
                height={720}
                width={1400}
                className="mx-auto rounded-2xl object-cover h-full object-left-top"
                draggable={false}
              />
            </ContainerScroll>
          </div>
        </div>
      </section>

      <section className="space-y-6 pb-6 pt-6 md:pb-12 md:pt-14 lg:py-12 mx-auto">
        {/* <BentoGridComponent /> */}
        <div className="container flex flex-col max-w-[84rem] items-center gap-4 text-center">
          <h1 className="font-heading text-2xl sm:text-5xl md:text-6xl lg:text-7xl  font-semibold">
          Everything you need for website monitoring and optimization
          </h1>
          <BigTabsComponent />
        </div>
      </section>

      <section className="space-y-6 pb-6 pt-6 md:pb-12 md:pt-14 lg:py-32">
      <div className="max-w-5xl mx-auto px-8">
      <HoverEffect items={projects} />
    </div>
      </section>

      <section className="space-y-6 py-8 dark:bg-transparent md:py-12 lg:py-24 relative overflow-hidden">
        <div className="mx-auto w-full max-w-[2560px] px-4 md:px-[34px] relative  mt-16 overflow-hidden pb-4 md:my-28 md:py-28">
          <div className="absolute -z-10 top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%] blur-[40px] dark:h-[35rem] dark:blur-[90px] bg-white dark:bg-black rounded-full items-center  md:mx-auto md:w-[45rem] md:gap-8 md:text-center max-w-[1440px] h-[27rem]"></div>
          <div className="rounded-full flex flex-col items-center text-center md:mx-auto md:w-[30rem] py-10 md:gap-8 md:text-center">
            <h3 className="border-none leading-[100%] text-[40px] md:text-5xl lg:text-[50px] xl:text-6xl font-semibold">
              Connect your favorite apps to get notification
            </h3>
            <span className="mt-8 md:mt-0">
              WEBSPY currently works on these; in the future,  apps notification
              will be added.
            </span>
            <div>
              <span className="rounded-4xl font-matter text-md items-center justify-center px-8 py-4 font-semibold uppercase leading-none [&amp;_svg]:ml-[8px] [&amp;_svg]:mt-[1px] shadow-fill hover:shadow-input-grow border-primary-700 active:shadow-input-shrink h-[50px] border-2 bg-gray-50 transition-all duration-150 ease-in-out will-change-transform hover:translate-y-[-2px] active:translate-y-[2px] active:duration-100 md:h-[80px]  group hidden max-w-[330px] cursor-pointer !text-black md:mx-auto md:flex">
                Explore all apps
                <div className="ml-2 scale-150">
                  <svg
                    className="stroke-black stroke-2"
                    fill="none"
                    width="10"
                    height="10"
                    viewBox="0 0 10 10"
                    aria-hidden="true"
                  >
                    <path
                      className="opacity-0 transition group-hover:opacity-100"
                      d="M0 5h7"
                    ></path>
                    <path
                      className="transition group-hover:translate-x-[3px]"
                      d="M1 1l4 4-4 4"
                    ></path>
                  </svg>
                </div>
              </span>
            </div>
          </div>

          {/* <div className="flex flex-col gap-4 opacity-70 overflow-hidden relative"> */}
          <div className="-z-20 -mx-4 flex flex-col items-center justify-center gap-2 py-2 md:absolute md:inset-0 md:mx-0 md:gap-7 opacity-55 ">
            <LandingPageIcons />
            <div className="relative left-52 sm:-left-10 md:-left-15">
              <LandingPageIcons />
            </div>
            <div className="relative -left-5 sm:left-10 md:left-15">
              <LandingPageIcons />
            </div>
            <LandingPageIcons />
          </div>
        </div>
      </section>
      </div>
    </div>
  );
};

export default LandingPage;
